apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-pi
  namespace: minecraft
  annotations:
    kubesailEditorUid: 32572248-9102-4fe9-8d20-f2bbd10b4487
    kubesail.com/template: loopDelicious/minecraft-raspberry-pi:v25
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-world
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          tty: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world
              subPath: world
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world_nether
              subPath: world_nether
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/world_the_end
              subPath: world_the_end
            - name: world
              mountPath: /app/cuberite/build-cuberite/Server/players
              subPath: players
          ports:
            - name: game-port
              containerPort: 25565
              hostPort: 25565
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 1
              memory: 2000Mi
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: PAPER
