---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  namespace: minecraft
  labels:
    app: minecraft
  annotations:
    kubesailEditorUid: c6561719-a4a8-4d0e-9773-041fcab39973
    kubesail.com/template: loopDelicious/minecraft-raspberry-pi:v25
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
